"""add_jimeng_tables

Revision ID: 6fc1adfb106d
Revises: d7462fa176a0
Create Date: 2025-08-18 10:14:45.078645

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db


# revision identifiers, used by Alembic.
revision: str = "6fc1adfb106d"
down_revision: Union[str, None] = "d7462fa176a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 创建 jimeng_config 表
    op.create_table(
        "jimeng_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False, default=False),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("api_key", sa.Text(), nullable=True),
        sa.Column("default_duration", sa.String(10), nullable=False, default="5"),
        sa.Column(
            "default_aspect_ratio", sa.String(10), nullable=False, default="16:9"
        ),
        sa.Column("default_cfg_scale", sa.Float(), nullable=False, default=0.5),
        sa.Column("credits_per_5s", sa.Integer(), nullable=False, default=30),
        sa.Column("credits_per_10s", sa.Integer(), nullable=False, default=60),
        sa.Column("max_concurrent_tasks", sa.Integer(), nullable=False, default=5),
        sa.Column("task_timeout", sa.Integer(), nullable=False, default=600000),
        sa.Column("query_interval", sa.Integer(), nullable=False, default=10000),
        sa.Column("detected_api_path", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.PrimaryKeyConstraint("id"),
    )

    # 2. 创建 jimeng_tasks 表
    op.create_table(
        "jimeng_tasks",
        sa.Column("id", sa.String(255), nullable=False),
        sa.Column("user_id", sa.String(255), nullable=False),
        sa.Column("action", sa.String(50), nullable=False),
        sa.Column("status", sa.String(50), nullable=False, default="submitted"),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("duration", sa.String(10), nullable=False),
        sa.Column("aspect_ratio", sa.String(10), nullable=False),
        sa.Column("cfg_scale", sa.Float(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("input_image", sa.Text(), nullable=True),
        sa.Column("external_task_id", sa.String(255), nullable=True),
        sa.Column("video_url", sa.Text(), nullable=True),
        sa.Column("progress", sa.String(50), nullable=True, default="0%"),
        sa.Column("fail_reason", sa.Text(), nullable=True),
        sa.Column("credits_cost", sa.Integer(), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=True),
        sa.Column("submit_time", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("complete_time", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.PrimaryKeyConstraint("id"),
    )

    # 3. 创建索引
    op.create_index("idx_jimeng_tasks_user_id", "jimeng_tasks", ["user_id"])
    op.create_index("idx_jimeng_tasks_status", "jimeng_tasks", ["status"])
    op.create_index("idx_jimeng_tasks_created_at", "jimeng_tasks", ["created_at"])
    op.create_index(
        "idx_jimeng_tasks_user_status", "jimeng_tasks", ["user_id", "status"]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除索引
    op.drop_index("idx_jimeng_tasks_user_status", "jimeng_tasks")
    op.drop_index("idx_jimeng_tasks_created_at", "jimeng_tasks")
    op.drop_index("idx_jimeng_tasks_status", "jimeng_tasks")
    op.drop_index("idx_jimeng_tasks_user_id", "jimeng_tasks")

    # 删除表
    op.drop_table("jimeng_tasks")
    op.drop_table("jimeng_config")

    # ### end Alembic commands ###
