"""add_tool_access_control_column

Revision ID: 70c7b727736e
Revises: 6fc1adfb106d
Create Date: 2025-08-18 12:08:37.435087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db


# revision identifiers, used by Alembic.
revision: str = "70c7b727736e"
down_revision: Union[str, None] = "6fc1adfb106d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 为 tool 表添加 access_control 列
    with op.batch_alter_table("tool", schema=None) as batch_op:
        batch_op.add_column(sa.Column("access_control", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除 tool 表的 access_control 列
    with op.batch_alter_table("tool", schema=None) as batch_op:
        batch_op.drop_column("access_control")

    # ### end Alembic commands ###
