"""add_jimeng_watermark_fields

Revision ID: 8e9f2a5b3c1d
Revises: 22c97ff924a3
Create Date: 2025-08-23 14:30:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db

# revision identifiers, used by Alembic.
revision: str = "8e9f2a5b3c1d"
down_revision: Union[str, None] = "22c97ff924a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add watermark column to jimeng_tasks table
    op.add_column(
        "jimeng_tasks",
        sa.Column(
            "watermark",
            sa.Boolean(),
            default=False,
            nullable=False,
            comment="是否包含水印",
        ),
    )

    # Add default_watermark column to jimeng_config table
    op.add_column(
        "jimeng_config",
        sa.Column(
            "default_watermark",
            sa.Boolean(),
            default=False,
            nullable=False,
            comment="默认水印设置",
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove columns in reverse order
    op.drop_column("jimeng_config", "default_watermark")
    op.drop_column("jimeng_tasks", "watermark")

    # ### end Alembic commands ###
