"""init dreamwork tables

Revision ID: a1b2c3d4e5f6
Revises: 97c08d196e3d
Create Date: 2025-08-16 10:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = "97c08d196e3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 创建 dreamwork_config 表
    op.create_table(
        "dreamwork_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True, default=False),
        sa.Column("base_url", sa.String(500), nullable=True),
        sa.Column("api_key", sa.Text(), nullable=True),
        sa.Column(
            "text_to_image_model",
            sa.String(100),
            nullable=True,
            default="doubao-seedream-3-0-t2i-250415",
        ),
        sa.Column(
            "image_to_image_model",
            sa.String(100),
            nullable=True,
            default="doubao-seededit-3-0-i2i-250628",
        ),
        sa.Column("default_size", sa.String(20), nullable=True, default="1024x1024"),
        sa.Column("default_guidance_scale", sa.Float(), nullable=True, default=2.5),
        sa.Column("watermark_enabled", sa.Boolean(), nullable=True, default=True),
        sa.Column("credits_per_generation", sa.Integer(), nullable=True, default=10),
        sa.Column("max_concurrent_tasks", sa.Integer(), nullable=True, default=5),
        sa.Column("task_timeout", sa.Integer(), nullable=True, default=300000),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # 创建 dreamwork_tasks 表
    op.create_table(
        "dreamwork_tasks",
        sa.Column("id", sa.String(50), nullable=False),
        sa.Column("user_id", sa.String(50), nullable=True),
        sa.Column("action", sa.String(50), nullable=True),
        sa.Column("status", sa.String(50), nullable=True, default="SUBMITTED"),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("model", sa.String(100), nullable=True),
        sa.Column("size", sa.String(20), nullable=True),
        sa.Column("guidance_scale", sa.Float(), nullable=True),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column("watermark", sa.Boolean(), nullable=True, default=True),
        sa.Column("image_base64", sa.Text(), nullable=True),  # 输入图片(图生图)
        sa.Column("credits_cost", sa.Integer(), nullable=True, default=0),
        sa.Column("submit_time", sa.DateTime(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("finish_time", sa.DateTime(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("image_data", sa.Text(), nullable=True),  # base64格式的生成图片
        sa.Column("fail_reason", sa.Text(), nullable=True),
        sa.Column("request_data", sa.JSON(), nullable=True),
        sa.Column("response_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # 创建索引
    op.create_index(
        "idx_dreamwork_user_created", "dreamwork_tasks", ["user_id", "created_at"]
    )
    op.create_index(
        "idx_dreamwork_status_updated", "dreamwork_tasks", ["status", "updated_at"]
    )
    op.create_index("ix_dreamwork_tasks_user_id", "dreamwork_tasks", ["user_id"])

    # 创建 dreamwork_credits 表
    op.create_table(
        "dreamwork_credits",
        sa.Column("id", sa.String(50), nullable=False),
        sa.Column("user_id", sa.String(50), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("balance", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(200), nullable=True),
        sa.Column("task_id", sa.String(50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # 创建积分表索引
    op.create_index(
        "idx_dreamwork_user_created_credits",
        "dreamwork_credits",
        ["user_id", "created_at"],
    )
    op.create_index("ix_dreamwork_credits_user_id", "dreamwork_credits", ["user_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除表
    op.drop_table("dreamwork_credits")
    op.drop_table("dreamwork_tasks")
    op.drop_table("dreamwork_config")
    # ### end Alembic commands ###
