"""add_cloud_storage_tables

Revision ID: a1b2c3d4e5f8
Revises: 6fc1adfb106d
Create Date: 2025-08-18 21:30:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db


# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f8"
down_revision: Union[str, None] = "a1b2c3d4e5f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 创建云存储配置表
    op.create_table(
        "cloud_storage_config",
        sa.Column("id", sa.String(255), nullable=False),
        sa.Column("provider", sa.String(50), nullable=False),  # 'tencent-cos'
        sa.Column("enabled", sa.Boolean(), nullable=False, default=False),
        # 腾讯云COS配置
        sa.Column("secret_id", sa.Text(), nullable=True),
        sa.Column("secret_key", sa.Text(), nullable=True),
        sa.Column("region", sa.String(50), nullable=True),  # 'ap-beijing'
        sa.Column("bucket", sa.String(255), nullable=True),
        sa.Column("domain", sa.Text(), nullable=True),  # 自定义域名
        # 上传配置
        sa.Column("auto_upload", sa.Boolean(), nullable=False, default=True),
        sa.Column("allowed_types", sa.JSON(), nullable=True),  # ['image/*', 'video/*']
        sa.Column(
            "max_file_size", sa.BigInteger(), nullable=False, default=104857600
        ),  # 100MB
        # 路径配置
        sa.Column("base_path", sa.String(255), nullable=False, default="generated/"),
        sa.Column("image_path", sa.String(255), nullable=False, default="images/"),
        sa.Column("video_path", sa.String(255), nullable=False, default="videos/"),
        sa.Column("created_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.PrimaryKeyConstraint("id"),
    )

    # 2. 创建生成文件记录表
    op.create_table(
        "generated_files",
        sa.Column("id", sa.String(255), nullable=False),
        sa.Column("user_id", sa.String(255), nullable=False),
        # 文件基本信息
        sa.Column("filename", sa.String(255), nullable=False),
        sa.Column("original_filename", sa.String(255), nullable=True),
        sa.Column("file_type", sa.String(20), nullable=False),  # 'image', 'video'
        sa.Column("mime_type", sa.String(100), nullable=True),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        # 存储信息
        sa.Column("storage_provider", sa.String(50), nullable=False, default="local"),
        sa.Column("local_path", sa.Text(), nullable=True),  # 本地备份路径
        sa.Column("cloud_url", sa.Text(), nullable=True),  # COS访问URL
        sa.Column("cloud_path", sa.Text(), nullable=True),  # COS存储路径
        # 关联信息
        sa.Column(
            "source_type", sa.String(50), nullable=False
        ),  # 'midjourney', 'kling', 'jimeng', 'dreamwork'
        sa.Column("source_task_id", sa.String(255), nullable=True),  # 关联任务ID
        # 元数据和状态
        sa.Column("file_metadata", sa.JSON(), nullable=True),  # 扩展数据
        sa.Column(
            "status", sa.String(20), nullable=False, default="pending"
        ),  # 'pending', 'uploaded', 'failed'
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.PrimaryKeyConstraint("id"),
    )

    # 3. 创建索引优化查询性能
    op.create_index("idx_generated_files_user_id", "generated_files", ["user_id"])
    op.create_index(
        "idx_generated_files_source",
        "generated_files",
        ["source_type", "source_task_id"],
    )
    op.create_index("idx_generated_files_status", "generated_files", ["status"])
    op.create_index("idx_generated_files_created_at", "generated_files", ["created_at"])
    op.create_index(
        "idx_generated_files_user_status", "generated_files", ["user_id", "status"]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除索引
    op.drop_index("idx_generated_files_user_status", "generated_files")
    op.drop_index("idx_generated_files_created_at", "generated_files")
    op.drop_index("idx_generated_files_status", "generated_files")
    op.drop_index("idx_generated_files_source", "generated_files")
    op.drop_index("idx_generated_files_user_id", "generated_files")

    # 删除表
    op.drop_table("generated_files")
    op.drop_table("cloud_storage_config")

    # ### end Alembic commands ###
