"""add_inpainting_tables

Revision ID: a1e2f3g4h5i6
Revises: merge_heads_final
Create Date: 2025-08-22 09:30:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db

# revision identifiers, used by Alembic.
revision: str = "a1e2f3g4h5i6"
down_revision: Union[str, None] = "merge_heads_final"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 创建 inpainting_config 表
    op.create_table(
        "inpainting_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "enabled",
            sa.Boolean(),
            nullable=True,
            default=False,
            comment="是否启用涂抹消除功能",
        ),
        sa.Column(
            "base_url",
            sa.String(500),
            nullable=True,
            default="https://api.linkapi.org",
            comment="API基础URL",
        ),
        sa.Column("api_key", sa.Text(), nullable=True, comment="API密钥"),
        sa.Column(
            "credits_per_task",
            sa.Integer(),
            nullable=True,
            default=50,
            comment="每个涂抹消除任务消耗积分",
        ),
        sa.Column(
            "max_concurrent_tasks",
            sa.Integer(),
            nullable=True,
            default=3,
            comment="最大并发任务数",
        ),
        sa.Column(
            "task_timeout",
            sa.Integer(),
            nullable=True,
            default=300000,
            comment="任务超时时间(毫秒)",
        ),
        sa.Column(
            "default_steps",
            sa.Integer(),
            nullable=True,
            default=30,
            comment="默认采样步数",
        ),
        sa.Column(
            "default_strength",
            sa.Float(),
            nullable=True,
            default=0.8,
            comment="默认强度",
        ),
        sa.Column(
            "default_scale",
            sa.Float(),
            nullable=True,
            default=7.0,
            comment="默认文本描述程度",
        ),
        sa.Column(
            "default_quality",
            sa.String(10),
            nullable=True,
            default="M",
            comment="默认质量(H/M/L)",
        ),
        sa.Column(
            "default_dilate_size",
            sa.Integer(),
            nullable=True,
            default=15,
            comment="默认mask膨胀半径",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # 2. 创建 inpainting_tasks 表
    op.create_table(
        "inpainting_tasks",
        sa.Column("id", sa.String(50), nullable=False, comment="任务ID"),
        sa.Column("user_id", sa.String(50), nullable=False, comment="用户ID"),
        sa.Column("task_id", sa.String(100), nullable=True, comment="外部任务ID"),
        sa.Column(
            "status",
            sa.String(50),
            nullable=True,
            default="submitted",
            comment="任务状态",
        ),
        sa.Column("task_status_msg", sa.Text(), nullable=True, comment="状态消息"),
        sa.Column("input_image_url", sa.Text(), nullable=True, comment="输入图片URL"),
        sa.Column("mask_image_url", sa.Text(), nullable=True, comment="Mask图片URL"),
        sa.Column(
            "uploaded_input_url",
            sa.Text(),
            nullable=True,
            comment="上传的输入图片云存储URL",
        ),
        sa.Column(
            "uploaded_mask_url",
            sa.Text(),
            nullable=True,
            comment="上传的Mask图片云存储URL",
        ),
        sa.Column("steps", sa.Integer(), nullable=True, default=30, comment="采样步数"),
        sa.Column("strength", sa.Float(), nullable=True, default=0.8, comment="强度"),
        sa.Column(
            "scale", sa.Float(), nullable=True, default=7.0, comment="文本描述程度"
        ),
        sa.Column(
            "quality", sa.String(10), nullable=True, default="M", comment="质量(H/M/L)"
        ),
        sa.Column(
            "dilate_size",
            sa.Integer(),
            nullable=True,
            default=15,
            comment="mask膨胀半径",
        ),
        sa.Column("seed", sa.Integer(), nullable=True, default=0, comment="随机种子"),
        sa.Column(
            "result_image_url", sa.Text(), nullable=True, comment="生成结果图片URL"
        ),
        sa.Column(
            "cloud_result_url", sa.Text(), nullable=True, comment="云存储结果图片URL"
        ),
        sa.Column("fail_reason", sa.Text(), nullable=True, comment="失败原因"),
        sa.Column(
            "credits_cost", sa.Integer(), nullable=True, default=0, comment="消耗积分"
        ),
        sa.Column("submit_time", sa.DateTime(), nullable=True, comment="提交时间"),
        sa.Column("start_time", sa.DateTime(), nullable=True, comment="开始处理时间"),
        sa.Column("finish_time", sa.DateTime(), nullable=True, comment="完成时间"),
        sa.Column("request_data", sa.Text(), nullable=True, comment="请求数据JSON"),
        sa.Column("response_data", sa.Text(), nullable=True, comment="响应数据JSON"),
        sa.Column("properties", sa.JSON(), nullable=True, comment="扩展属性"),
        sa.Column(
            "progress", sa.String(20), nullable=True, default="0%", comment="进度"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # 3. 创建索引
    op.create_index("idx_inpainting_tasks_user_id", "inpainting_tasks", ["user_id"])
    op.create_index("idx_inpainting_tasks_status", "inpainting_tasks", ["status"])
    op.create_index(
        "idx_inpainting_tasks_created_at", "inpainting_tasks", ["created_at"]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除索引
    op.drop_index("idx_inpainting_tasks_created_at", "inpainting_tasks")
    op.drop_index("idx_inpainting_tasks_status", "inpainting_tasks")
    op.drop_index("idx_inpainting_tasks_user_id", "inpainting_tasks")

    # 删除表
    op.drop_table("inpainting_tasks")
    op.drop_table("inpainting_config")

    # ### end Alembic commands ###
