"""add phone and verification codes

Revision ID: b8f3a2c9d1e0
Revises: 97c08d196e3d
Create Date: 2025-08-17 10:30:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "b8f3a2c9d1e0"
down_revision: Union[str, None] = "97c08d196e3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 给user表添加phone字段
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("phone", sa.String(), nullable=True))
        batch_op.create_index("ix_user_phone", ["phone"], unique=True)
        batch_op.create_unique_constraint("uq_user_phone", ["phone"])

    # 2. 创建手机验证码表
    op.create_table(
        "phone_verification_codes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("purpose", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=True, default=0),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.Column("used_at", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # 创建索引以优化查询性能
    with op.batch_alter_table("phone_verification_codes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_phone_verification_codes_phone", ["phone"], unique=False
        )
        batch_op.create_index(
            "ix_phone_verification_codes_expires_at", ["expires_at"], unique=False
        )
        batch_op.create_index(
            "ix_phone_verification_codes_user_id", ["user_id"], unique=False
        )
        batch_op.create_index(
            "ix_phone_verification_codes_purpose", ["purpose"], unique=False
        )
        batch_op.create_index(
            "ix_phone_verification_codes_created_at", ["created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除手机验证码表的索引
    with op.batch_alter_table("phone_verification_codes", schema=None) as batch_op:
        batch_op.drop_index("ix_phone_verification_codes_created_at")
        batch_op.drop_index("ix_phone_verification_codes_purpose")
        batch_op.drop_index("ix_phone_verification_codes_user_id")
        batch_op.drop_index("ix_phone_verification_codes_expires_at")
        batch_op.drop_index("ix_phone_verification_codes_phone")

    # 删除手机验证码表
    op.drop_table("phone_verification_codes")

    # 删除user表的phone字段
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_phone", type_="unique")
        batch_op.drop_index("ix_user_phone")
        batch_op.drop_column("phone")

    # ### end Alembic commands ###
