"""add_comfyui_tables

Revision ID: c1d2e3f4g5h6
Revises: g3h4i5j6k7l8
Create Date: 2025-09-01 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db

# revision identifiers, used by Alembic.
revision: str = "c1d2e3f4g5h6"
down_revision: Union[str, None] = "g3h4i5j6k7l8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 创建ComfyUI配置表
    op.create_table(
        "comfyui_config",
        sa.Column("id", sa.String(255), nullable=False),
        sa.Column("access_key", sa.Text(), nullable=False, comment="哩布API访问凭证"),
        sa.Column("secret_key", sa.Text(), nullable=False, comment="哩布API访问密钥"),
        sa.Column(
            "base_url",
            sa.String(500),
            nullable=False,
            default="https://openapi.liblibai.cloud",
            comment="API基础URL",
        ),
        sa.Column(
            "enabled", sa.Boolean(), nullable=False, default=False, comment="启用状态"
        ),
        sa.Column(
            "timeout",
            sa.Integer(),
            nullable=False,
            default=300,
            comment="请求超时时间（秒）",
        ),
        sa.Column(
            "max_concurrent_tasks",
            sa.Integer(),
            nullable=False,
            default=5,
            comment="最大并发任务数",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.PrimaryKeyConstraint("id"),
    )

    # 2. 创建ComfyUI工作流管理表
    op.create_table(
        "comfyui_workflows",
        sa.Column("id", sa.String(255), nullable=False),
        sa.Column(
            "template_uuid", sa.String(255), nullable=False, comment="哩布模板UUID"
        ),
        sa.Column(
            "workflow_uuid", sa.String(255), nullable=False, comment="哩布工作流UUID"
        ),
        sa.Column("name", sa.String(255), nullable=False, comment="工作流名称"),
        sa.Column("description", sa.Text(), nullable=True, comment="工作流描述"),
        sa.Column("category", sa.String(100), nullable=True, comment="分类"),
        sa.Column("preview_image", sa.Text(), nullable=True, comment="预览图URL"),
        # 参数配置
        sa.Column(
            "parameter_schema", sa.JSON(), nullable=False, comment="参数结构定义"
        ),
        sa.Column("default_params", sa.JSON(), nullable=True, comment="默认参数值"),
        # 积分配置
        sa.Column(
            "base_credits",
            sa.Integer(),
            nullable=False,
            default=10,
            comment="基础积分消耗",
        ),
        sa.Column(
            "complexity_multiplier",
            sa.Float(),
            nullable=False,
            default=1.0,
            comment="复杂度系数",
        ),
        # 状态配置
        sa.Column(
            "enabled", sa.Boolean(), nullable=False, default=True, comment="启用状态"
        ),
        sa.Column(
            "is_public",
            sa.Boolean(),
            nullable=False,
            default=False,
            comment="是否公开显示",
        ),
        sa.Column(
            "sort_order", sa.Integer(), nullable=False, default=0, comment="排序权重"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.PrimaryKeyConstraint("id"),
    )

    # 3. 创建ComfyUI任务执行表
    op.create_table(
        "comfyui_tasks",
        sa.Column("id", sa.String(255), nullable=False),
        sa.Column("user_id", sa.String(255), nullable=False, comment="用户ID"),
        sa.Column("workflow_id", sa.String(255), nullable=False, comment="工作流ID"),
        sa.Column(
            "generate_uuid",
            sa.String(255),
            nullable=True,
            comment="哩布API返回的任务UUID",
        ),
        # 任务参数
        sa.Column("input_params", sa.JSON(), nullable=False, comment="输入参数"),
        sa.Column("template_uuid", sa.String(255), nullable=False, comment="模板UUID"),
        sa.Column(
            "workflow_uuid", sa.String(255), nullable=False, comment="工作流UUID"
        ),
        # 任务状态
        sa.Column(
            "status",
            sa.String(20),
            nullable=False,
            default="PENDING",
            comment="任务状态",
        ),
        sa.Column(
            "generate_status", sa.Integer(), nullable=True, comment="哩布返回的状态码"
        ),
        sa.Column(
            "percent_completed",
            sa.Float(),
            nullable=False,
            default=0.0,
            comment="完成进度",
        ),
        # 结果数据
        sa.Column("output_images", sa.JSON(), nullable=True, comment="输出图片列表"),
        sa.Column("output_videos", sa.JSON(), nullable=True, comment="输出视频列表"),
        sa.Column("cloud_images", sa.JSON(), nullable=True, comment="云存储图片URLs"),
        sa.Column("cloud_videos", sa.JSON(), nullable=True, comment="云存储视频URLs"),
        # 消耗信息
        sa.Column("credits_cost", sa.Integer(), nullable=True, comment="积分消耗"),
        sa.Column("generation_time", sa.Float(), nullable=True, comment="生成耗时"),
        # 错误信息
        sa.Column("error_message", sa.Text(), nullable=True, comment="错误信息"),
        sa.Column(
            "retry_count", sa.Integer(), nullable=False, default=0, comment="重试次数"
        ),
        sa.Column(
            "liblib_response", sa.JSON(), nullable=True, comment="哩布API原始响应"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.Column("completed_at", sa.DateTime(), nullable=True, comment="完成时间"),
        sa.PrimaryKeyConstraint("id"),
    )

    # 4. 创建ComfyUI积分管理表
    op.create_table(
        "comfyui_credits",
        sa.Column("id", sa.String(255), nullable=False),
        sa.Column("user_id", sa.String(255), nullable=False, comment="用户ID"),
        sa.Column(
            "credits_balance",
            sa.Integer(),
            nullable=False,
            default=0,
            comment="剩余积分",
        ),
        sa.Column(
            "total_used", sa.Integer(), nullable=False, default=0, comment="已使用积分"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.PrimaryKeyConstraint("id"),
    )

    # 5. 创建索引优化查询性能
    op.create_index(
        "idx_comfyui_workflows_public_enabled",
        "comfyui_workflows",
        ["is_public", "enabled"],
    )
    op.create_index("idx_comfyui_workflows_category", "comfyui_workflows", ["category"])
    op.create_index(
        "idx_comfyui_tasks_user_status", "comfyui_tasks", ["user_id", "status"]
    )
    op.create_index(
        "idx_comfyui_tasks_workflow_status", "comfyui_tasks", ["workflow_id", "status"]
    )
    op.create_index(
        "idx_comfyui_tasks_generate_uuid", "comfyui_tasks", ["generate_uuid"]
    )
    op.create_index("idx_comfyui_tasks_created_at", "comfyui_tasks", ["created_at"])
    op.create_index("idx_comfyui_credits_user_id", "comfyui_credits", ["user_id"])

    # 6. 插入默认ComfyUI配置
    op.execute(
        """
        INSERT INTO comfyui_config 
        (id, access_key, secret_key, base_url, enabled, timeout, max_concurrent_tasks) 
        VALUES 
        ('default', '', '', 'https://openapi.liblibai.cloud', 1, 300, 5)
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除索引
    op.drop_index("idx_comfyui_credits_user_id", "comfyui_credits")
    op.drop_index("idx_comfyui_tasks_created_at", "comfyui_tasks")
    op.drop_index("idx_comfyui_tasks_generate_uuid", "comfyui_tasks")
    op.drop_index("idx_comfyui_tasks_workflow_status", "comfyui_tasks")
    op.drop_index("idx_comfyui_tasks_user_status", "comfyui_tasks")
    op.drop_index("idx_comfyui_workflows_category", "comfyui_workflows")
    op.drop_index("idx_comfyui_workflows_public_enabled", "comfyui_workflows")

    # 删除表
    op.drop_table("comfyui_credits")
    op.drop_table("comfyui_tasks")
    op.drop_table("comfyui_workflows")
    op.drop_table("comfyui_config")

    # ### end Alembic commands ###
