"""remove_comfyui_credits_table

Revision ID: d3e4f5g6h7i8
Revises: c1d2e3f4g5h6
Create Date: 2025-01-15 15:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d3e4f5g6h7i8"
down_revision: Union[str, None] = "c1d2e3f4g5h6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除ComfyUI独立积分表相关索引
    try:
        op.drop_index("idx_comfyui_credits_user_id", "comfyui_credits")
    except:
        pass

    # 删除ComfyUI独立积分表
    try:
        op.drop_table("comfyui_credits")
    except:
        pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 重新创建ComfyUI积分管理表
    op.create_table(
        "comfyui_credits",
        sa.Column("id", sa.String(255), nullable=False),
        sa.Column("user_id", sa.String(255), nullable=False, comment="用户ID"),
        sa.Column(
            "credits_balance",
            sa.Integer(),
            nullable=False,
            default=0,
            comment="剩余积分",
        ),
        sa.Column(
            "total_used", sa.Integer(), nullable=False, default=0, comment="已使用积分"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.PrimaryKeyConstraint("id"),
    )

    # 重新创建索引
    op.create_index("idx_comfyui_credits_user_id", "comfyui_credits", ["user_id"])

    # ### end Alembic commands ###
