"""add_kling_tables

Revision ID: d7462fa176a0
Revises: 33de2e0ea2f5
Create Date: 2025-08-18 10:14:11.159920

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db


# revision identifiers, used by Alembic.
revision: str = "d7462fa176a0"
down_revision: Union[str, None] = "33de2e0ea2f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 创建 kling_config 表
    op.create_table(
        "kling_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True, default=False),
        sa.Column(
            "base_url", sa.String(500), nullable=True, default="https://api.klingai.com"
        ),
        sa.Column("api_key", sa.Text(), nullable=True),
        sa.Column(
            "text_to_video_model", sa.String(100), nullable=True, default="kling-v1"
        ),
        sa.Column(
            "image_to_video_model", sa.String(100), nullable=True, default="kling-v1"
        ),
        sa.Column("default_mode", sa.String(20), nullable=True, default="std"),
        sa.Column("default_duration", sa.String(10), nullable=True, default="5"),
        sa.Column("default_aspect_ratio", sa.String(20), nullable=True, default="16:9"),
        sa.Column("default_cfg_scale", sa.Float(), nullable=True, default=0.5),
        sa.Column("credits_per_std_5s", sa.Integer(), nullable=True, default=50),
        sa.Column("credits_per_std_10s", sa.Integer(), nullable=True, default=100),
        sa.Column("credits_per_pro_5s", sa.Integer(), nullable=True, default=100),
        sa.Column("credits_per_pro_10s", sa.Integer(), nullable=True, default=200),
        sa.Column("model_credits_config", sa.JSON(), nullable=True),
        sa.Column("max_concurrent_tasks", sa.Integer(), nullable=True, default=3),
        sa.Column("task_timeout", sa.Integer(), nullable=True, default=600000),
        sa.Column("detected_api_path", sa.String(200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # 2. 创建 kling_tasks 表
    op.create_table(
        "kling_tasks",
        sa.Column("id", sa.String(50), nullable=False),
        sa.Column("user_id", sa.String(50), nullable=False),
        sa.Column("external_task_id", sa.String(100), nullable=True),
        sa.Column("action", sa.String(50), nullable=False),
        sa.Column("status", sa.String(50), nullable=True, default="SUBMITTED"),
        sa.Column("task_status_msg", sa.Text(), nullable=True),
        sa.Column("model_name", sa.String(100), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("negative_prompt", sa.Text(), nullable=True),
        sa.Column("cfg_scale", sa.Float(), nullable=True),
        sa.Column("mode", sa.String(20), nullable=True),
        sa.Column("duration", sa.String(10), nullable=True),
        sa.Column("aspect_ratio", sa.String(20), nullable=True),
        sa.Column("input_image", sa.Text(), nullable=True),
        sa.Column("image_tail", sa.Text(), nullable=True),
        sa.Column("static_mask", sa.Text(), nullable=True),
        sa.Column("dynamic_masks", sa.JSON(), nullable=True),
        sa.Column("camera_control", sa.JSON(), nullable=True),
        sa.Column("credits_cost", sa.Integer(), nullable=True, default=0),
        sa.Column("submit_time", sa.DateTime(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("finish_time", sa.DateTime(), nullable=True),
        sa.Column("video_id", sa.String(100), nullable=True),
        sa.Column("video_url", sa.Text(), nullable=True),
        sa.Column("video_duration", sa.String(10), nullable=True),
        sa.Column("fail_reason", sa.Text(), nullable=True),
        sa.Column("request_data", sa.Text(), nullable=True),
        sa.Column("response_data", sa.Text(), nullable=True),
        sa.Column("properties", sa.JSON(), nullable=True),
        sa.Column("progress", sa.String(20), nullable=True, default="0%"),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # 3. 创建 kling_credits 表
    op.create_table(
        "kling_credits",
        sa.Column("id", sa.String(50), nullable=False),
        sa.Column("user_id", sa.String(50), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(200), nullable=True),
        sa.Column("task_id", sa.String(50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # 4. 创建索引
    op.create_index("idx_kling_tasks_user_id", "kling_tasks", ["user_id"])
    op.create_index("idx_kling_tasks_status", "kling_tasks", ["status"])
    op.create_index("idx_kling_credits_user_id", "kling_credits", ["user_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除索引
    op.drop_index("idx_kling_credits_user_id", "kling_credits")
    op.drop_index("idx_kling_tasks_status", "kling_tasks")
    op.drop_index("idx_kling_tasks_user_id", "kling_tasks")

    # 删除表
    op.drop_table("kling_credits")
    op.drop_table("kling_tasks")
    op.drop_table("kling_config")

    # ### end Alembic commands ###
