"""enable_comfyui_by_default

Revision ID: e5f6g7h8i9j0
Revises: d3e4f5g6h7i8
Create Date: 2025-01-15 16:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e5f6g7h8i9j0"
down_revision: Union[str, None] = "d3e4f5g6h7i8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 更新现有的ComfyUI配置，将enabled设置为True
    try:
        op.execute(
            """
            UPDATE comfyui_config 
            SET enabled = 1 
            WHERE id = 'default' AND enabled = 0
            """
        )
    except Exception:
        # 如果表不存在或更新失败，忽略
        pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 将ComfyUI配置的enabled设置回False
    try:
        op.execute(
            """
            UPDATE comfyui_config 
            SET enabled = 0 
            WHERE id = 'default'
            """
        )
    except Exception:
        # 如果表不存在或更新失败，忽略
        pass

    # ### end Alembic commands ###
