"""add_user_phone_column

Revision ID: ef6fab585ac1
Revises: 70c7b727736e
Create Date: 2025-08-18 12:15:17.101992

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db


# revision identifiers, used by Alembic.
revision: str = "ef6fab585ac1"
down_revision: Union[str, None] = "70c7b727736e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 为 user 表添加 phone 列（安全检查）
    connection = op.get_bind()
    inspector = sa.inspect(connection)

    if "user" in inspector.get_table_names():
        existing_columns = [col["name"] for col in inspector.get_columns("user")]
        existing_indexes = [idx["name"] for idx in inspector.get_indexes("user")]

        with op.batch_alter_table("user", schema=None) as batch_op:
            if "phone" not in existing_columns:
                batch_op.add_column(sa.Column("phone", sa.String(), nullable=True))
                print("Added phone column to user table")
            else:
                print("phone column already exists in user table")

            # 为 phone 列创建唯一索引
            if "ix_user_phone" not in existing_indexes:
                batch_op.create_index("ix_user_phone", ["phone"], unique=True)
                print("Added unique index ix_user_phone")
            else:
                print("Index ix_user_phone already exists")
    else:
        print("user table does not exist, skipping phone column addition")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除 user 表的 phone 列和索引
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index("ix_user_phone")
        batch_op.drop_column("phone")

    # ### end Alembic commands ###
